### ISSUE TITLE
Battleship orientation incorrect

### ISSUE THREAD

**Issue by ayetee** [jpvillavicencio/battleship#1]
1. Create new board.
2. Create battleship (size 4) with vertical orientation.

Actual Result:
Battleship is placed horizontally.

Expected Result:
Battleship is placed vertically.

**Comment by ayetee** [comment]
@jpvillavicencio can I get an ETA on this fix?

**Comment by jpvillavicencio** [comment]
Resolved

**Comment by ayetee** [comment]
thanks @jpvillavicencio appreciate the quick resolve
